export enum ActionType {
    SET_PERSONS = 'SET_PERSONS',
    LOAD_PERSONS = 'LOAD_PERSONS',
    LOAD_PERSON_DETAIL = 'LOAD_PERSON_DETAIL',
    LOAD_MAPS = 'LOAD_MAPS',
    SET_PERSON_DETAIL = 'SET_PERSON_DETAIL',
    SET_CLIENTS = 'SET_CLIENTS',
    LOAD_CLIENTS = 'LOAD_CLIENTS',
    ADD_ERROR = 'ADD_ERROR',
    ADD_PERSON = 'ADD_PERSON',
    ASSIGN_PERSON = 'ASSIGN_PERSON',
    SET_MAPS = 'SET_MAPS',
    LOAD_KILL_STATS = 'LOAD_KILL_STATS',
    SET_KILL_STATS = 'SET_KILL_STATS'
}
