export enum ChallengeType {
    GENERAL_TOTALKILLS = 1,
    GENERAL_TOTALDEATHS = 2,
    GENERAL_TOTALGAMES = 3,

    // gametypes
    GAMETYPES_FFA_WINS = 101,
    GAMETYPES_TOURNEY_WINS = 102,
    GAMETYPES_TDM_WINS = 103,
    GAMETYPES_CTF_WINS = 104,
    GAMETYPES_1FCTF_WINS = 105,
    GAMETYPES_OVERLOAD_WINS = 106,
    GAMETYPES_HARVESTER_WINS = 107,
    GAMETYPES_ELIMINATION_WINS = 108,
    GAMETYPES_CTF_ELIMINATION_WINS = 109,
    GAMETYPES_LMS_WINS = 110,
    GAMETYPES_DD_WINS = 111,
    GAMETYPES_DOM_WINS = 112,

    // weapons
    WEAPON_GAUNTLET_KILLS = 201,
    WEAPON_MACHINEGUN_KILLS = 202,
    WEAPON_SHOTGUN_KILLS = 203,
    WEAPON_GRANADE_KILLS = 204,
    WEAPON_ROCKET_KILLS = 205,
    WEAPON_LIGHTNING_KILLS = 206,
    WEAPON_PLASMA_KILLS = 207,
    WEAPON_RAIL_KILLS = 208,
    WEAPON_BFG_KILLS = 209,
    WEAPON_GRAPPLE_KILLS = 210,
    WEAPON_CHAINGUN_KILLS = 211,
    WEAPON_NAILGUN_KILLS = 212,
    WEAPON_MINE_KILLS = 213,
    WEAPON_PUSH_KILLS = 214,
    WEAPON_INSTANT_RAIL_KILLS = 215,
    WEAPON_TELEFRAG_KILLS = 216,
    WEAPON_CRUSH_KILLS = 217,

    // awards
    // gauntlet is not here as it is the same as WEAPON_GAUNTLET_KILLS
    AWARD_IMPRESSIVE = 301,
    AWARD_EXCELLENT = 302,
    AWARD_CAPTURE = 303,
    AWARD_ASSIST = 304,
    AWARD_DEFENCE = 305,

    // powerups
    POWERUP_QUAD_KILL = 401,
    POWERUP_SPEED_KILL = 402,
    POWERUP_FLIGHT_KILL = 403,
    POWERUP_INVIS_KILL = 404,
    POWERUP_MULTI_KILL = 405,
    POWERUP_COUNTER_QUAD = 406,
    POWERUP_COUNTER_SPEED = 407,
    POWERUP_COUNTER_FLIGHT = 408,
    POWERUP_COUNTER_INVIS = 409,
    POWERUP_COUNTER_ENVIR = 410,
    POWERUP_COUNTER_REGEN = 411,
    POWERUP_COUNTER_MULTI = 412,

    // FFA awards
    FFA_TOP3 = 501,
    // enemy gets fraglimit-1, player has at most fraglimit-2 but wins anyway
    FFA_FROMBEHIND = 502,
    // loose a match but have a positive kill ratio against the winner
    FFA_BETTERTHAN = 503,
    // get at least half of your kills for players in the best half of the scoreboard
    FFA_JUDGE = 504,
    // the oppesite
    FFA_CHEAPKILLER = 505
}
